### ISSUE TITLE
TorAndroid does not work on Android 10 device

### ISSUE THREAD

**Issue by mirsamantajbakhsh** [mirsamantajbakhsh/TorAndroid#5]
Someone sent me an email about this issue and thankfully donated to the project.

He himself fixed the issue and I mentioning it here due to he has not GitHub account.

The fix was this:

Adding a tag to manifest application section:
```xml
android:extractNativeLibs = "true"
```

**Comment by adriadam10** [comment]
That solve the problem, but now my app is all black. I can't see anything.
I run this code:
`private void tor() {
        HiddenService hs1 = new HiddenService();
        hs1.addHiddenServiceMapping(21, new Address("127.0.0.1", 2121));

        List<HiddenService> hss = new ArrayList<>();
        hss.add(hs1);

        TorProxy.TorBuilder tb = new TorProxy.TorBuilder()
                .setDebuggable(true)
                .setSOCKsPort(9050)
                .setServices(hss);

        final TorProxy tp = tb.build(this);
        tp.init();
        try {
            tp.start(new IConnectionDone() {
                @Override
                public void onSuccess() {
                    torstatus_tv.setTextColor(Color.parseColor("#00FF00"));
                    Log.d("MSTTOR", "Everything is OK!");
                    String addresses = "";
                    for (HiddenService hs : tp.getHiddenServices()) {
                        addresses += hs.getHiddenServiceAddress() + ":\r\n";
                    }
                    Toast.makeText(getApplicationContext(),"Connected to tor", Toast.LENGTH_LONG).show();
                }
                @Override
                public void onFailure(Exception ex) {
                    Toast.makeText(getApplicationContext(), "Tor error", Toast.LENGTH_LONG).show();
                    torstatus_tv.setTextColor(Color.parseColor("#0000ff"));
                }
            });
        } catch (IOException ignored) {
        }
    }`
